### ISSUE TITLE
Does it have an installler?

### ISSUE THREAD

**Issue by rodrigovidal** [ratishphilip/nvmsharp#2]
Hi Ratish, your project looks really cool! 

Today the only way to use it is building from source? I think it would be nice to have an installer.

What do you think?

**Comment by ratishphilip** [comment]
Hi rodrigovidal,
Yes it is a good idea. Thanks for the suggestion. 
However, if you visit the CodeProject site (http://www.codeproject.com/Articles/1045296/NVMSharp), there is a link where you can download the executable.

**Comment by jsbeckr** [comment]
I would like to see another distribution channel than codeproject, because you have to sign in to download the file. Putting an executable on github or onedrive would be sufficient for now. :+1: 

Nice piece of software by the way :)

**Comment by ratishphilip** [comment]
Added executable to the repository.
